-- MARVISPACE v5 — server-side shopping cart (per browser session cookie)
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS cart_sessions (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cart_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  session_id VARCHAR(64) NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  label VARCHAR(255) NOT NULL,
  size VARCHAR(32) NOT NULL DEFAULT '',
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  qty INT UNSIGNED NOT NULL DEFAULT 1,
  image VARCHAR(512) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_cart_line (session_id, product_id, size),
  INDEX idx_cart_items_session (session_id),
  CONSTRAINT fk_cart_items_session FOREIGN KEY (session_id) REFERENCES cart_sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
