#!/usr/bin/env python3
"""Download Google Fonts woff2 files and rewrite CSS to local /assets/fonts paths."""
from __future__ import annotations

import hashlib
import pathlib
import re
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "fonts"
CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Syne:wght@400..700"
    "&family=Bricolage+Grotesque:opsz,wght@12..96,400..700"
    "&family=IBM+Plex+Mono:wght@400;500;600"
    "&family=Vazirmatn:wght@400..700"
    "&display=swap"
)
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    req = urllib.request.Request(CSS_URL, headers={"User-Agent": UA})
    css = urllib.request.urlopen(req, timeout=60).read().decode("utf-8")
    urls = sorted(set(re.findall(r"https://fonts\.gstatic\.com/s/[^)\"']+", css)))
    url_map = {}
    for url in urls:
        digest = hashlib.md5(url.encode()).hexdigest()[:10]
        family = url.split("/s/")[1].split("/")[0]
        name = f"{family}-{digest}.woff2"
        dest = OUT / name
        if not dest.exists() or dest.stat().st_size < 1000:
            urllib.request.urlretrieve(url, dest)
        url_map[url] = "/assets/fonts/" + name
        print(f"{name} {dest.stat().st_size}")
    local_css = css
    for url, local in url_map.items():
        local_css = local_css.replace(url, local)
    header = (
        "/* Generated by tools/vendor-fonts.py — self-hosted Google Fonts faces. "
        "Do not edit by hand. */\n"
    )
    (OUT / "faces.css").write_text(header + local_css, encoding="utf-8")
    print("wrote", OUT / "faces.css")


if __name__ == "__main__":
    main()
